import { PostType } from './interfaces/post.interface';
import { CommentType } from './interfaces/comment.interface';

export const postsData: PostType[] = [
  { id: '1', createDate: new Date('2024-01-01'), author: 'Alice', content: 'An adventurous journey through the rocky terrains and scenic landscapes.', imageUrl: 'https://picsum.photos/200/300', likes: 15 },
  { id: '2', createDate: new Date('2024-01-02'), author: 'Bob', content: 'A relaxing day at the beach with clear skies and gentle waves.', imageUrl: 'https://picsum.photos/200/301', likes: 20 },
  { id: '3', createDate: new Date('2024-01-03'), author: 'Charlie', content: 'Just another day in the city.', likes: 0 },
  { id: '4', createDate: new Date('2024-01-04'), author: 'Dana', content: 'Exploring the hidden trails in the forest and finding a beautiful waterfall.', imageUrl: 'https://picsum.photos/200/302', likes: 30 },
  { id: '5', createDate: new Date('2024-01-05'), author: 'Eve', content: 'A cozy evening by the fireplace with a good book.', imageUrl: 'https://picsum.photos/200/303', likes: 25 },
  { id: '6', createDate: new Date('2024-01-06'), author: 'Frank', content: 'Morning jog in the park with the fresh air and chirping birds.', likes: 0 },
  { id: '7', createDate: new Date('2024-01-07'), author: 'Grace', content: 'Visiting the art museum and admiring the beautiful paintings.', imageUrl: 'https://picsum.photos/200/304', likes: 40 },
  { id: '8', createDate: new Date('2024-01-08'), author: 'Hank', content: 'A quick snapshot of my homemade breakfast.', likes: 8 },
  { id: '9', createDate: new Date('2024-01-09'), author: 'Ivy', content: 'An evening walk along the riverside with stunning sunset views.', imageUrl: 'https://picsum.photos/200/305', likes: 35 },
  { id: '10', createDate: new Date('2024-01-10'), author: 'Jack', content: 'Enjoying a cup of coffee at my favorite café.', likes: 12 },
  { id: '11', createDate: new Date('2024-01-11'), author: 'Kathy', content: 'Just finished a great book. Can’t wait to read the next one!', likes: 22 },
  { id: '12', createDate: new Date('2024-01-12'), author: 'Liam', content: 'Caught a glimpse of the beautiful sunrise today.', imageUrl: 'https://picsum.photos/200/306', likes: 17 },
  { id: '13', createDate: new Date('2024-01-13'), author: 'Mia', content: 'Had a fun day hiking with friends!', imageUrl: 'https://picsum.photos/200/307', likes: 29 },
  { id: '14', createDate: new Date('2024-01-14'), author: 'Noah', content: 'Playing video games all weekend. What a blast!', likes: 5 },
  { id: '15', createDate: new Date('2024-01-15'), author: 'Olivia', content: 'Learning to cook a new recipe. Wish me luck!', likes: 3 },
  { id: '16', createDate: new Date('2024-01-16'), author: 'Paul', content: 'Spent the day at the zoo. So many cute animals!', imageUrl: 'https://picsum.photos/200/308', likes: 45 },
  { id: '17', createDate: new Date('2024-01-17'), author: 'Quinn', content: 'Just got back from a vacation in the mountains. Feeling refreshed!', imageUrl: 'https://picsum.photos/200/309', likes: 12 },
  { id: '18', createDate: new Date('2024-01-18'), author: 'Ryan', content: 'Trying out new coffee blends. This one is amazing!', likes: 8 },
  { id: '19', createDate: new Date('2024-01-19'), author: 'Sophia', content: 'A beautiful day for a bike ride!', imageUrl: 'https://picsum.photos/200/310', likes: 21 },
  { id: '20', createDate: new Date('2024-01-20'), author: 'Tyler', content: 'Visited a new restaurant and loved the food.', likes: 19 },
  { id: '21', createDate: new Date('2024-01-21'), author: 'Uma', content: 'Gardening is my new favorite hobby!', likes: 10 },
  { id: '22', createDate: new Date('2024-01-22'), author: 'Victor', content: 'Can’t wait for the weekend to relax.', likes: 0 },
  { id: '23', createDate: new Date('2024-01-23'), author: 'Wendy', content: 'Just adopted a puppy! Excited for new adventures.', imageUrl: 'https://picsum.photos/200/311', likes: 30 },
  { id: '24', createDate: new Date('2024-01-24'), author: 'Xander', content: 'Working on my fitness goals this year.', likes: 14 },
  { id: '25', createDate: new Date('2024-01-25'), author: 'Yara', content: 'A cozy rainy day with some tea and a good movie.', likes: 5 },
  { id: '26', createDate: new Date('2024-01-26'), author: 'Zane', content: 'Exploring local markets for fresh produce.', imageUrl: 'https://picsum.photos/200/312', likes: 18 },
  { id: '27', createDate: new Date('2024-01-27'), author: 'Ava', content: 'Just finished a tough workout, feeling great!', likes: 26 },
  { id: '28', createDate: new Date('2024-01-28'), author: 'Ben', content: 'Going for a walk in the snow, beautiful scenery!', imageUrl: 'https://picsum.photos/200/313', likes: 11 },
  { id: '29', createDate: new Date('2024-01-29'), author: 'Cleo', content: 'Finally tried sushi for the first time, loved it!', likes: 22 },
  { id: '30', createDate: new Date('2024-01-30'), author: 'Derek', content: 'Planning my next travel adventure. Where to go next?', likes: 8 },
];

export const commentsData: CommentType[] = [
  { id: 'c1', content: 'Great post!', author: 'John Doe', postId: '1' },
  { id: 'c2', content: 'Really enjoyed this.', author: 'Jane Smith', postId: '1' },
  { id: 'c3', content: 'Very informative.', author: 'Emily Davis', postId: '2' },
  { id: 'c4', content: 'Love this!', author: 'Michael Brown', postId: '2' },
  { id: 'c5', content: 'Thanks for sharing.', author: 'Sarah Wilson', postId: '3' },
  { id: 'c6', content: 'Amazing!', author: 'David Johnson', postId: '3' },
  { id: 'c7', content: 'Really helpful.', author: 'Emma Moore', postId: '4' },
  { id: 'c8', content: 'Great insights.', author: 'Daniel Taylor', postId: '4' },
  { id: 'c9', content: 'Wonderful post.', author: 'Olivia Martinez', postId: '5' },
  { id: 'c10', content: 'Very well written.', author: 'Lucas Garcia', postId: '5' },
];